# Google. Scale: %100
EASY_GOOGLE_BOARD = 10, 8
MEDIUM_GOOGLE_BOARD = 18, 14
HARD_GOOGLE_BOARD = 24, 20

EASY_GOOGLE_BOARD_LOCATION = ((988, 576), (1551, 1026))
MEDUIM_GOOGLE_BOARD_LOCATION = ((932, 539), (1606, 1063))
HARD_GOOGLE_BOARD_LOCATION = ((895, 489), (1644, 1113))

EASY_GOOGLE_BOMB_COUNT = 10
MEDIUM_GOOGLE_BOMB_COUNT = 40
HARD_GOOGLE_BOMB_COUNT = 99


# Minesweeper Online. Scale: 250%
EASY_MO_BOARD = 9, 9
MEDUIM_MO_BOARD = 16, 16
HARD_MO_BOARD = 30, 16

EASY_MO_BOARD_LOCATION = ((), ())
MEDUIM_MO_BOARD_LOCATION = ((), ())
HARD_MO_BOARD_LOCATION = ((), ())

EASY_GOOGLE_BOMB_COUNT = 10
MEDIUM_GOOGLE_BOMB_COUNT = 40
HARD_GOOGLE_BOMB_COUNT = 99



EASY_GOOGLE = EASY_GOOGLE_BOARD, EASY_GOOGLE_BOARD_LOCATION, EASY_GOOGLE_BOMB_COUNT
MEDIUM_GOOGLE = MEDIUM_GOOGLE_BOARD, MEDUIM_GOOGLE_BOARD_LOCATION, MEDIUM_GOOGLE_BOMB_COUNT
HARD_GOOGLE = HARD_GOOGLE_BOARD, HARD_GOOGLE_BOARD_LOCATION, HARD_GOOGLE_BOMB_COUNT


DIFFICULTY = EASY_GOOGLE